version: '3'

services:
  lokal:
    build:
      context: .
    container_name: lokal
    restart: always
    environment:
      # HOST must be set!
      # - HOST=your.domain.com
      - DATABASE_URL=ecto://postgres:postgres@lokal-db/lokal
      # Use `docker run -it shibaobun/lokal /app/priv/random.sh` to generate a secret key base
      # - SECRET_KEY_BASE=change-me-this-is-really-important-seriously-change-it
      # uncomment to enable public sign ups, not recommended
      # - REGISTRATION=public
      # SMTP host must be set!
      # - SMTP_HOST=smtp.mailserver.tld
      # optional, default is 587
      # - SMTP_PORT=587
      # SMTP username/passwords must be set!
      # - SMTP_USERNAME=username
      # - SMTP_PASSWORD=password
      # optional, default is false
      # - SMTP_SSL=false
      # optional, default is format below
      # - EMAIL_FROM=no-reply@lokal.example.tld
      # optional, default is "Lokal"
      # - EMAIL_NAME=Lokal
    expose:
      - "4000"
    depends_on:
      - lokal-db

  lokal-db:
    image: postgres:13
    container_name: lokal-db
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_DB="lokal"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
